name: CI with Snyk and SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Snyk for dependency scanning
      uses: snyk/actions/python@master
      continue-on-error: true
      
      with:
        command: test
        args: --all-projects --severity-threshold=medium
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Run SonarQube analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=nanafilbert_new-repo-actions \
          -Dsonar.organization=new-repo-github-actions \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}