name: Deploy to EC2

on:
  push:
    branches:
      - main

    
jobs:
  deploy:
    environment: prod

    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Deploy to EC2 Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            
            #Install Apache web server for launching the application
            sudo apt-get install -y nginx
            sudo systemctl daemon-reload
            sudo systemctl start nginx
            sudo systemctl enable nginx
            
            # Create nana directory if it doesn't exist
            mkdir -p nana
            cd nana

          
            sudo rm -rf /var/www/html/*
           
            # Move new files to /var/www/html
            sudo mv * /var/www/html
#