name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  TARGET_DIR: home  # 🔧 removed extra space in variable name
  EC2_USER: ubuntu

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Deploy to EC2 Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ vars.HOST_DNS }}
          REMOTE_USER: ${{ env.EC2_USER }}
          TARGET: ${{ env.TARGET_DIR }}

      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST_DNS }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd home
            sudo rm -rf /var/www/html/*
            sudo cp -r * /var/www/html/
#