name: npm Audit Security Check

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate package.json file
        run: npm init -y

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --audit-level=high > npm-audit.json
        continue-on-error: true

      - name: Upload Audit Report
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: npm-audit.json
          #