name: SonarQube Scan

on: 
  - push 
  - pull_request

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarCloud Scan
        run: |
         sonar-scanner \
         -Dsonar.projectKey=new-repo-github-actions \
         -Dsonar.organization=nanafilbert \
         -Dsonar.host.url=https://sonarcloud.io \
         -Dsonar.login=${{ secrets.SONAR_TOKEN }}

