name: Code Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # --- Run your tests ---
      - name: Run tests
        run: npm test || true  # prevent failure from stopping the workflow

      # --- Snyk security scan ---
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          command: test        # ✅ Required
          args: --all-projects # Optional: adjust based on your setup
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # --- SonarCloud scan ---
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          args: >
            -Dsonar.projectKey=nanafilbert_new-repo-actions
            -Dsonar.organization=new-repo-github-actions
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
